# Generated by Django 4.0.1 on 2022-02-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0002_locations_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='lng',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
