# Generated by Django 4.0.1 on 2022-02-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0003_locations_lat_locations_lng_locations_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='address',
        ),
        migrations.AddField(
            model_name='locations',
            name='state',
            field=models.CharField(default='TX', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='street',
            field=models.CharField(default='1515', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='zip_code',
            field=models.IntegerField(default=77030),
            preserve_default=False,
        ),
    ]
