# Generated by Django 4.0.1 on 2022-02-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0004_remove_locations_address_locations_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='lng',
            field=models.IntegerField(),
        ),
    ]
