# Generated by Django 4.0.1 on 2022-02-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0005_alter_locations_lat_alter_locations_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='city',
            field=models.CharField(default='City', max_length=100),
            preserve_default=False,
        ),
    ]
