# Generated by Django 4.0.1 on 2022-02-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0006_locations_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='lng',
            field=models.FloatField(),
        ),
    ]
