# Generated by Django 4.0.1 on 2022-02-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0007_alter_locations_lat_alter_locations_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
