# Generated by Django 4.0.1 on 2022-02-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0008_locations_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
